<?php
use Drupal\Core\Form\FormStateInterface;
/**
 * Implements hook_theme().
 */
function plentiful_theme($existing, $type, $theme, $path) {
  return [
    'plentiful_list' => [
      'variables' => [
        'results' => [],
        'labels' => [],
      ],
    ],
  ];
}

/**
 * Implements hook_form_alter().
 */
function plentiful_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  // if ($form_id === 'block_form') {}
}